spring:
  datasource:
    username: ${B_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    servlet:
        multipart:
        max-file-size: 10MB
        max-request-size: 10MB    
  
    